services:
 mariadb:
  build: ./requirements/mariadb/
   # context: ./requirements/mariadb/
   # dockerfile: Dockerfile
  container_name: mariadb #_inception_akasiota
  restart: no
  expose:
   - "3306"
  secrets:
   - wp_mysql_password
   - wp_mysql_root_password
  env_file:
   - .env
  volumes:
   - mysql_volume:/var/lib/mysql
  networks:
   - inception_net_ak
       
 wordpress:
   build: ./requirements/wordpress
   container_name: wordpress #_inception_akasiota
   restart: no
   depends_on:
    mariadb:
     condition: service_started
     restart: true
   expose:
    - "9000"
   secrets:
    - wp_mysql_password
    - wp_admin_password
   env_file:
    - .env
   volumes:
    - wp_volume:/var/www/html
   networks:
    - inception_net_ak
 
 nginx:
  build: ./requirements/nginx/
  container_name: nginx #_inception_akasiota
  restart: no
  depends_on:
   wordpress:
    condition: service_started
    restart: true
  ports:
   - "443:443"
  volumes:
   - wp_volume:/var/www/html
  networks:
   - inception_net_ak

volumes:
 mysql_volume:
  driver: local
  driver_opts:
   type: none
   device: /home/${USER}/data/mariadb
   o: bind
 wp_volume:
  driver: local
  driver_opts:
   type: none
   device: /home/${USER}/data/wordpress
   o: bind

networks:
 inception_net_ak:

secrets:
 wp_mysql_password:
  file: ./.secrets/wp_mysql_password.txt
 wp_mysql_root_password:
  file: ./.secrets/wp_mysql_root_password.txt
 wp_admin_password:
  file: ./.secrets/wp_admin_password.txt
