services:
 mariadb:
  build:
   ./requirements/mariadb/
   # context: ./requirements/mariadb/
   # dockerfile: Dockerfile
  container_name: mariadb_inception_akasiota
  restart: always
  env_file:
   - .env
  volumes:
   - db_volume:/var/lib/mysql
  networks:
   - inception_net_ak
       
  wordpress:
   build: ./requirements/wordpress
   container_name: wp_inception_akasiota
   restart: always
   depends_on:
    mariadb:
     condition: service_healthy
     restart: true
    expose:
     - "9000"
   volumes:
    - wp_volume:/var/www/html
   networks:
    - inception_net_ak
 nginx:
  build: ./requirements/nginx/
  container_name: nginx_inception_akasiota
  restart: always
  depends_on:
   wordpress:
    condition: service_healthy
    restart: true
  ports:
   - "443:443"
  volumes:
   - wp_volume:/var/www/html
  networks:
   - inception_net_ak

volumes:
 db_volume:
 wp_volume:

networks:
 inception_net_ak:

